version: '3.8'
services:
  postgresql: #Database
    image: postgres:14.1-alpine 
    container_name: postgresql_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:  #Client for Postgresql
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin-data: